version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Devops  # Database name as specified in your application.properties
    ports:
      - 3306:3306
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: archen7/tp-foyer:1.0.0  # Your Docker image on DockerHub
    restart: on-failure
    ports:
      - 8089:8089  # Exposed port for your app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/Devops?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - mynetwork

volumes:
  db:  # Named volume for MySQL data

networks:
  mynetwork:
    driver: bridge  # Default driver, suitable for communication within the same host
