version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  app-foyer:
    image: ahmedzmerli/5arctic5-g5  # Utilisation du nom d'image spécifié
    container_name: app-foyer
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username": "root",
              "spring.datasource.password": "root",
              "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
              "spring.jpa.hibernate.ddl-auto": "update"
            }'
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  db_data:
